/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_reservation (void);
GtkWidget* create_reservation_vol (void);
GtkWidget* create_reservation_hotel (void);
GtkWidget* create_reservation_vol_reserver (void);
GtkWidget* create_reservation_hotel_reserver (void);
GtkWidget* create_mes_reservation_hotel (void);
GtkWidget* create_mes_reservation_vol (void);
GtkWidget* create_modification_vols (void);
GtkWidget* create_modification_hotel (void);
