/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_aceuil (void);
GtkWidget* create_ajout (void);
GtkWidget* create_modification (void);
GtkWidget* create_supression (void);
GtkWidget* create_affichage (void);
GtkWidget* create_modification2 (void);
